"""
Evaluate task quality using multi-model council (Kimi K2.5 + GPT-5.2).

Scores task on category-specific criteria and returns pass/fail with suggestions.

Usage:
    # CLI
    python -m emtom.cli.judge_task task.json [--working-dir DIR] [--threshold 0.65]

    # Programmatic
    from emtom.cli.judge_task import run
    result = run("task.json", working_dir="/tmp/work")
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

from emtom.cli import CLIResult, failure, success
from emtom.cli.task_metadata import compute_strict_tom_metadata
from emtom.cli.validate_task import static_validate_trajectory


SKIPPABLE_STEPS = {"pddl", "tom", "simulation", "structure", "llm-council"}


def run(
    task_file: str,
    working_dir: str = None,
    scene_file: str = None,
    trajectory_dir: str = None,
    models: Optional[List[str]] = None,
    threshold: float = 0.65,
    difficulty: Optional[str] = None,
    user_query: Optional[str] = None,
    required_tom_level: Optional[int] = None,
    verified_trajectory_hash: Optional[str] = None,
    skip_regenerate_golden: bool = False,
    skip_steps: Optional[List[str]] = None,
) -> CLIResult:
    """
    Evaluate task quality using multi-model council.

    Args:
        task_file: Path to task JSON file.
        working_dir: Optional working directory (for scene data, trajectory lookup).
        scene_file: Optional explicit scene data JSON file.
        trajectory_dir: Optional path to benchmark rollout data.
        models: Council model names (default: ["kimi-k2.5", "gpt-5.2"]).
        threshold: Overall score threshold for passing.
        difficulty: Difficulty level context (easy/medium/hard).
        user_query: Optional user query the task should align with.
        required_tom_level: Optional strict tom_level the task must satisfy.
        verified_trajectory_hash: Previously simulator-verified trajectory hash.
            When the newly regenerated plan matches this hash, simulator
            verification is skipped.
        skip_regenerate_golden: Assume golden trajectory has already been
            regenerated by the caller and skip the regeneration step here.

    Returns:
        CLIResult with data keys: passed, overall_score, threshold,
        models, model_results, suggestions, disagreements.
    """
    _skip = set(skip_steps or [])

    task_path = Path(task_file)
    if not task_path.exists():
        return failure(f"Task file not found: {task_file}")

    try:
        with open(task_path) as f:
            task_data = json.load(f)
    except json.JSONDecodeError as e:
        return failure(f"Invalid JSON: {e}")

    scene_data = _load_scene_data(working_dir, scene_file)

    # Deterministic strict PDDL verification is the first judge gate.
    if "pddl" in _skip:
        verify_result = {"success": True, "data": {"skipped": True, "reason": "--remove pddl"}, "error": None}
    else:
        from emtom.cli.verify_pddl import run as verify_pddl_run

        verify_result = verify_pddl_run(task_file, working_dir=working_dir)
        if not verify_result["success"]:
            # In lightweight taskgen environments we may not have the strict FD backend.
            # Allow falling back to structural verification so task authors can proceed.
            err = (verify_result.get("error") or "")
            if "Strict proof backend unavailable" in err:
                verify_result = {"success": True, "data": {"warning": err, "proof_backend": "structural_only"}, "error": None}
            else:
                return verify_result

    if "tom" in _skip:
        strict_tom = {"tom_level": required_tom_level, "skipped": True, "reason": "--remove tom"}
    else:
        try:
            strict_tom = compute_strict_tom_metadata(task_data, scene_data=scene_data)
        except Exception as e:
            return failure(f"Strict ToM verification failed: {e}")

    strict_tom_level = strict_tom.get("tom_level")
    if False:
        pass
    if "tom" not in _skip and required_tom_level is not None and strict_tom_level != required_tom_level:
        return failure(
            f"Strict tom_level is {strict_tom_level} but required tom_level is {required_tom_level}.",
            data={
                "required_tom_level": required_tom_level,
                "computed_tom_level": strict_tom_level,
                "strict_tom_verification": strict_tom,
            },
        )

    golden_status: Dict[str, Any] = {
        "regenerated": False,
        "sim_verification_ran": False,
        "sim_verified": False,
        "spec_hash": None,
        "trajectory_hash": None,
    }
    if "simulation" in _skip:
        golden_status["skipped"] = True
        golden_status["reason"] = "--remove simulation"
        golden_status["sim_verified"] = True
    elif skip_regenerate_golden:
        metadata = task_data.get("golden_trajectory_metadata", {})
        if isinstance(metadata, dict):
            golden_status["spec_hash"] = metadata.get("spec_hash")
            golden_status["trajectory_hash"] = metadata.get("trajectory_hash")
        golden_status["regenerated"] = False
    else:
        try:
            from emtom.pddl.planner import regenerate_golden_trajectory

            regen = regenerate_golden_trajectory(
                task_data,
                scene_data=scene_data,
                source="judge",
                task_file=task_file,
            )
            golden_status.update(
                {
                    "regenerated": True,
                    "spec_hash": regen.get("spec_hash"),
                    "trajectory_hash": regen.get("trajectory_hash"),
                    "num_steps": regen.get("num_steps"),
                }
            )
        except Exception as e:
            return failure(
                f"Failed to regenerate golden trajectory from task spec: {e}",
                data={"golden_trajectory": golden_status},
            )

        needs_sim_verification = (
            not verified_trajectory_hash
            or golden_status["trajectory_hash"] != verified_trajectory_hash
        )
        if needs_sim_verification:
            golden_status["sim_verification_ran"] = True
            verification = _verify_golden_trajectory_in_sim(
                task_file=task_file,
                working_dir=working_dir,
                task_data=task_data,
                scene_data=scene_data,
            )
            if not verification["success"]:
                err = verification.get("error") or ""
                # Lightweight environments may lack simulator deps (hydra/habitat).
                # If so, skip sim verification.
                if ("No module named 'hydra'" in err or "No module named \"hydra\"" in err                     or "No module named 'habitat'" in err or "No module named \"habitat\"" in err):
                    golden_status["sim_verified"] = True
                    golden_status["sim_verification_skipped_reason"] = f"Skipped sim verification due to missing deps: {err}"
                else:
                    payload = verification.get("data") or {}
                    payload.setdefault("stage", "golden_trajectory_verification")
                    payload["golden_trajectory"] = golden_status
                    return failure(err, data=payload)
            # If simulator verification succeeded (or we skipped it due to missing
            # simulator deps), record the result without overriding the earlier
            # decision.
            if verification["success"]:
                golden_status["sim_verified"] = True
                golden_status["sim_verification"] = verification.get("data")
        else:
            golden_status["sim_verified"] = True
            golden_status["sim_verification_skipped_reason"] = (
                "Regenerated trajectory hash matches the last simulator-verified plan."
            )

    # Validate task structure before expensive LLM calls
    if "structure" not in _skip:
        from emtom.cli.validate_task import validate

        validation = validate(task_data, scene_data)
        if not validation["success"]:
            return validation

    if "llm-council" in _skip:
        # Skip the LLM council entirely — auto-pass with perfect score.
        result_data: Dict[str, Any] = {
            "passed": True,
            "overall_score": 1.0,
            "threshold": threshold,
            "models": [],
            "pddl_verification": verify_result.get("data", {}),
            "strict_tom_verification": strict_tom,
            "golden_trajectory": golden_status,
            "model_results": {},
            "suggestions": [],
            "summary": "PASS - LLM council skipped (--remove llm-council)",
            "skipped_steps": sorted(_skip),
        }
        if working_dir:
            from datetime import datetime
            judgments_dir = Path(working_dir) / "judgments"
            judgments_dir.mkdir(parents=True, exist_ok=True)
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            judgment_file = judgments_dir / f"judgment_{timestamp}.json"
            with open(judgment_file, "w") as f:
                json.dump(result_data, f, indent=2)
            result_data["judgment_file"] = str(judgment_file)
        return success(result_data)

    # Find latest trajectory dir if not explicitly provided
    traj_path = None
    if trajectory_dir:
        traj_path = Path(trajectory_dir)
    elif working_dir:
        trajectories_dir = Path(working_dir) / "agent_trajectories"
        if trajectories_dir.exists():
            task_dirs = sorted(trajectories_dir.glob("task_*"), key=lambda p: p.name)
            if task_dirs:
                run_dirs = sorted(task_dirs[-1].glob("run_*"), key=lambda p: p.name)
                if run_dirs:
                    traj_path = run_dirs[-1]

    # Create judge and evaluate
    from emtom.task_gen.judge import Judge

    judge = Judge(
        models=models,
        overall_threshold=threshold,
        difficulty=difficulty,
        user_query=user_query if not difficulty else None,
    )

    try:
        verdict = judge.evaluate(
            task_data,
            scene_data=scene_data,
            trajectory_dir=traj_path,
        )
    except RuntimeError as e:
        # RuntimeError from _aggregate means judge council is incomplete due to
        # infrastructure (429, timeout, etc.). Re-raise to kill the process
        # rather than letting the agent waste iterations on a non-task issue.
        if "council incomplete" in str(e) or "All judge models failed" in str(e):
            raise
        return failure(f"Evaluation failed: {e}")
    except Exception as e:
        return failure(f"Evaluation failed: {e}")

    # Build result
    result_data: Dict[str, Any] = {
        "passed": verdict.passed,
        "overall_score": verdict.overall_score,
        "threshold": judge.overall_threshold,
        "models": list(verdict.judgments.keys()),
        "pddl_verification": verify_result["data"],
        "strict_tom_verification": strict_tom,
        "model_results": {
            model: {
                "passed": j.is_valid,
                "score": j.overall_score,
            }
            for model, j in verdict.judgments.items()
        },
                "golden_trajectory": golden_status,
    }

    if verdict.disagreements:
        result_data["disagreements"] = verdict.disagreements

    if verdict.passed:
        result_data["summary"] = (
            f"PASS - All models agree task is valid (score: {verdict.overall_score:.2f})"
        )
    else:
        result_data["suggestions"] = verdict.suggestions
        result_data["summary"] = (
            f"FAIL - Task did not pass council (score: {verdict.overall_score:.2f})"
        )

    # Save verdict JSON
    verdict_dict = verdict.to_dict()

    if working_dir:
        judgments_dir = Path(working_dir) / "judgments"
        judgments_dir.mkdir(parents=True, exist_ok=True)
        from datetime import datetime

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        judgment_file = judgments_dir / f"judgment_{timestamp}.json"
        with open(judgment_file, "w") as f:
            json.dump(verdict_dict, f, indent=2)
        result_data["judgment_file"] = str(judgment_file)

    # Print status to stderr (human-readable)
    from emtom.task_gen.judge import Colors

    status = "PASS" if verdict.passed else "FAIL"
    color = Colors.GREEN if verdict.passed else Colors.RED
    print(
        f"\n{Colors.BOLD}{Colors.CYAN}=== Task Evaluation (Council) ==={Colors.RESET}",
        file=sys.stderr,
    )
    print(
        f"{Colors.BOLD}{color}{status}{Colors.RESET} - Score: {verdict.overall_score:.2f} "
        f"(threshold: {judge.overall_threshold})",
        file=sys.stderr,
    )
    print(f"Models: {', '.join(verdict.judgments.keys())}", file=sys.stderr)

    if verdict.disagreements:
        print(f"\n{Colors.YELLOW}Model disagreements:{Colors.RESET}", file=sys.stderr)
        for d in verdict.disagreements:
            print(f"  - {d}", file=sys.stderr)

    if not verdict.passed and verdict.suggestions:
        print(f"\n{Colors.YELLOW}Suggestions for improvement:{Colors.RESET}", file=sys.stderr)
        for i, suggestion in enumerate(verdict.suggestions, 1):
            print(f"  {i}. {suggestion}", file=sys.stderr)

    return success(result_data)


def _verify_golden_trajectory_in_sim(
    *,
    task_file: str,
    working_dir: Optional[str],
    task_data: Dict[str, Any],
    scene_data: Any,
) -> CLIResult:
    golden = task_data.get("golden_trajectory", [])
    if not golden:
        return failure("Deterministic planner produced empty trajectory.")

    static_errors = static_validate_trajectory(task_data, golden, scene_data)
    if static_errors:
        return failure(
            f"Golden trajectory static validation failed: {static_errors[0]}",
            data={"all_errors": static_errors},
        )

    if not working_dir:
        return failure(
            "Cannot simulator-verify golden trajectory without a working_dir."
        )

    num_agents = task_data.get("num_agents", 2)
    cmd = [
        sys.executable,
        "-m",
        "emtom.cli.verify_trajectory",
        str(task_file),
        "--working-dir",
        str(working_dir),
        "--config-name",
        f"examples/emtom_{num_agents}_robots",
    ]
    try:
        project_root = Path(__file__).resolve().parents[2]
        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=1200,
            cwd=str(project_root),
        )
    except subprocess.TimeoutExpired:
        return failure("Golden trajectory verification timed out (20 min). Possible navmesh issue.")
    except Exception as e:
        return failure(f"Golden trajectory verification subprocess error: {e}")

    try:
        stdout = proc.stdout
        json_start = stdout.find("{")
        if json_start >= 0:
            stdout = stdout[json_start:]
        result = json.loads(stdout)
    except (json.JSONDecodeError, ValueError):
        return failure(
            f"Failed to parse golden trajectory verification output: {proc.stderr[:500]}"
        )

    if result.get("success") and result.get("data", {}).get("valid"):
        return success(result["data"])

    return failure(
        result.get("error", "Golden trajectory verification failed."),
        data=result.get("data", {}),
    )


def _load_scene_data(working_dir: Optional[str], scene_file: Optional[str]):
    """Load SceneData from file if available."""
    scene_path = Path(scene_file) if scene_file else None
    if scene_path is None and working_dir:
        scene_path = Path(working_dir) / "current_scene.json"

    if scene_path and scene_path.exists():
        try:
            from emtom.task_gen.scene_loader import SceneData

            with open(scene_path) as sf:
                sd = json.load(sf)
            return SceneData(
                episode_id=sd["episode_id"],
                scene_id=sd["scene_id"],
                rooms=sd.get("rooms", []),
                furniture=sd.get("furniture", []),
                objects=sd.get("objects", []),
                articulated_furniture=sd.get("articulated_furniture", []),
                furniture_in_rooms=sd.get("furniture_in_rooms", {}),
                objects_on_furniture=sd.get("objects_on_furniture", {}),
                agent_spawns=sd.get("agent_spawns", {}),
            )
        except Exception:
            pass
    return None


if __name__ == "__main__":
    import argparse

    from emtom.cli import print_result

    parser = argparse.ArgumentParser(description="Evaluate task quality with multi-model council")
    parser.add_argument("task_file", help="Path to task JSON file")
    parser.add_argument("--working-dir", default=None, help="Working directory")
    parser.add_argument("--scene-file", default=None, help="Scene data JSON file")
    parser.add_argument("--trajectory-dir", default=None, help="Benchmark rollout data directory")
    parser.add_argument("--models", default=None, help="Comma-separated council models")
    parser.add_argument("--threshold", type=float, default=0.65, help="Score threshold (default: 0.65)")
    parser.add_argument("--difficulty", default=None, choices=["easy", "medium", "hard"])
    parser.add_argument("--required-tom-level", type=int, default=None)
    args = parser.parse_args()

    model_list = [m.strip() for m in args.models.split(",")] if args.models else None
    result = run(
        args.task_file,
        working_dir=args.working_dir,
        scene_file=args.scene_file,
        trajectory_dir=args.trajectory_dir,
        models=model_list,
        threshold=args.threshold,
        difficulty=args.difficulty,
        required_tom_level=args.required_tom_level,
    )
    print_result(result)
